## Testcafe deps https://devexpress.github.io/testcafe/documentation/continuous-integration/travis.html
dist: trusty
sudo: required

addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &

## Node https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js

node_js:
  - '12'
install:
  - npm install
script:
  - npm run eslint
  - npm run test:coverage
  - npm run test:e2e
  - npm run codecov
